################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
runtime/boot_code \
runtime/libgomp \
runtime/libgomp/config/bigpulp \
runtime/libgomp/config/pulp \
runtime/pulp-rt/drivers/camera \
runtime/pulp-rt/drivers/dolphin \
runtime/pulp-rt/drivers \
runtime/pulp-rt/drivers/gpio \
runtime/pulp-rt/drivers/hyper \
runtime/pulp-rt/drivers/i2c \
runtime/pulp-rt/drivers/i2s \
runtime/pulp-rt/drivers/pads \
runtime/pulp-rt/drivers/spim \
runtime/pulp-rt/drivers/uart \
runtime/pulp-rt/kernel \
runtime/pulp-rt/kernel/gap \
runtime/pulp-rt/kernel/oprecompkw/rt \
runtime/pulp-rt/kernel/oprecompkw/rtbare \
runtime/pulp-rt/kernel/oprecompkw/rttiny \
runtime/pulp-rt/kernel/or1k \
runtime/pulp-rt/kernel/or1k/rt \
runtime/pulp-rt/kernel/or1k/rtbare \
runtime/pulp-rt/kernel/or1k/rttiny \
runtime/pulp-rt/kernel/riscv \
runtime/pulp-rt/kernel/riscv/rt \
runtime/pulp-rt/kernel/riscv/rtbare \
runtime/pulp-rt/kernel/riscv/rttiny \
runtime/pulp-rt/kernel/vega \
runtime/pulp-rt/kernel/wolfe \
runtime/pulp-rt/libs/bench \
runtime/pulp-rt/libs/io \
runtime/pulp-rt/libs/omp \
runtime/pulp-rt-bare/drivers/camera \
runtime/pulp-rt-bare/drivers/dolphin \
runtime/pulp-rt-bare/drivers \
runtime/pulp-rt-bare/drivers/gpio \
runtime/pulp-rt-bare/drivers/hyper \
runtime/pulp-rt-bare/drivers/i2c \
runtime/pulp-rt-bare/drivers/i2s \
runtime/pulp-rt-bare/drivers/pads \
runtime/pulp-rt-bare/drivers/spim \
runtime/pulp-rt-bare/drivers/uart \
runtime/pulp-rt-bare/kernel \
runtime/pulp-rt-bare/kernel/gap \
runtime/pulp-rt-bare/kernel/oprecompkw/rt \
runtime/pulp-rt-bare/kernel/oprecompkw/rtbare \
runtime/pulp-rt-bare/kernel/oprecompkw/rttiny \
runtime/pulp-rt-bare/kernel/or1k \
runtime/pulp-rt-bare/kernel/or1k/rt \
runtime/pulp-rt-bare/kernel/or1k/rtbare \
runtime/pulp-rt-bare/kernel/or1k/rttiny \
runtime/pulp-rt-bare/kernel/riscv \
runtime/pulp-rt-bare/kernel/riscv/rt \
runtime/pulp-rt-bare/kernel/riscv/rtbare \
runtime/pulp-rt-bare/kernel/riscv/rttiny \
runtime/pulp-rt-bare/kernel/vega \
runtime/pulp-rt-bare/kernel/wolfe \
runtime/pulp-rt-bare/libs/bench \
runtime/pulp-rt-bare/libs/io \
runtime/pulp-rt-bare/libs/omp \
runtime/pulp-rt-tiny/drivers/camera \
runtime/pulp-rt-tiny/drivers/dolphin \
runtime/pulp-rt-tiny/drivers \
runtime/pulp-rt-tiny/drivers/gpio \
runtime/pulp-rt-tiny/drivers/hyper \
runtime/pulp-rt-tiny/drivers/i2c \
runtime/pulp-rt-tiny/drivers/i2s \
runtime/pulp-rt-tiny/drivers/pads \
runtime/pulp-rt-tiny/drivers/spim \
runtime/pulp-rt-tiny/drivers/uart \
runtime/pulp-rt-tiny/kernel \
runtime/pulp-rt-tiny/kernel/gap \
runtime/pulp-rt-tiny/kernel/oprecompkw/rt \
runtime/pulp-rt-tiny/kernel/oprecompkw/rtbare \
runtime/pulp-rt-tiny/kernel/oprecompkw/rttiny \
runtime/pulp-rt-tiny/kernel/or1k \
runtime/pulp-rt-tiny/kernel/or1k/rt \
runtime/pulp-rt-tiny/kernel/or1k/rtbare \
runtime/pulp-rt-tiny/kernel/or1k/rttiny \
runtime/pulp-rt-tiny/kernel/riscv \
runtime/pulp-rt-tiny/kernel/riscv/rt \
runtime/pulp-rt-tiny/kernel/riscv/rtbare \
runtime/pulp-rt-tiny/kernel/riscv/rttiny \
runtime/pulp-rt-tiny/kernel/vega \
runtime/pulp-rt-tiny/kernel/wolfe \
runtime/pulp-rt-tiny/libs/bench \
runtime/pulp-rt-tiny/libs/io \
runtime/pulp-rt-tiny/libs/omp \
src \

